### PR TITLE
Fixes type outputs

### PR DESCRIPTION
**Pull request by Rennzie**
Hey @DanielJDufour, 

This PR fixes how the type are built for public usage. These include `GeoRaster, GeoRasterLayerOptions, PixelValuesToColorFn `. It ensures they are available to import. I've also fixed a type error caused by the class itself not being typed correctly. Instantiating a new `georasterLayer` was throwing because it wasn't expecting any arguments. 

I've tested the build locally using `yarn link` and everything is working as expected. 

Please let me know if you've got any questions or comments on the implementation.

### CODE REVIEW

**Comment by DanielJDufour** [comment]
@Rennzie . Thank you!

**Comment by Rennzie** [comment]
> @Rennzie . Thank you!

No worries at all.

**Comment by DanielJDufour** [comment]
Hi, @Rennzie .  I'm a little confused on how to rebuild the library for publishing?  When do I run  `npm run build:types`?  I see that the `build` script runs `build:main` not `build:types`.

**Comment by Rennzie** [comment]
Hey @DanielJDufour, 

Running `build:main` runs `tsc` which is configured to output types as well as compile to js. I added a `build:types` command for convenience. 

You'd need to make these changes if you wanted `build:main` to only compiled js and `build:types` to handled type generation:

In .tsconfig remove: 

- `declarationMap`
- `declarationDir`
- `declaration`

Update `build:types` to: `tsc --emitDeclarationOnly --declaration --declarationMap --declarationDir dist`


Caveat here is you would declare the output destination in the `build:types` script and in the `.tsconfig`.

**Comment by DanielJDufour** [comment]
Thank you.  I understand a lot better now and republished!  We'll leave things the way they are now :-)

**Pull request merged**
